### PR TITLE
Updated the "The Team", "ACM Activities", "Event Calendar", "Achievements" pages

### PR DESCRIPTION
**Pull request by cajoshi**

### CODE REVIEW

**Comment by cajoshi** [comment]
Added Activities "Induction", "Hacktoberfest", "ESP" and "Awareness Sessions"

**Comment by cajoshi** [comment]
Also updated the timeline. Added names of events conducted in November.

**Comment by cajoshi** [comment]
Updated Achievements and added Video links for activities

**Comment by cajoshi** [comment]
Updated the team photos

**Review by JayeshShelar — APPROVED** [review]
Great job @cajoshi

**Pull request merged**
